global:
  scrape_interval: 15s

rule_files:
  - "postgres_alerts.yml"

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # à l'intérieur du réseau Docker

